{
    "name": "Job Offer Generator",
    "version": "1.3.0",
    "summary": "Generate offer letters from Recruitment applications",
    "category": "Human Resources/Recruitment",
    "author": "AutoGenerated",
    "depends": ["base","hr_recruitment", "hr_contract"],
    "data": [
        "security/ir.model.access.csv",
        "views/job_offer_views.xml",
        "reports/report_offer.xml",
        "reports/offer_templates.xml",
    ],
    "installable": True,
    "application": True,
}
